spring.application.name=ai-helpdesk
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_deskhelp
spring.datasource.username=rashid
spring.datasource.password=my-secret-pw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.ai.openai.enabled=false
server.port=8089